services:
  db:
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ToDo
    ports:
      - "3306:3306"
  web:
    build: ./ToDosApi
    ports:
      - "8000:80"
    links:
      - "db"
  front:
    build: ./to-dos-app
    ports:
      - "3000:3000"